[simulation]
dt			= 0.01
output.dt	= 0.01
output.dir	= "output"

[launcher]
length	= 5
elevation	= 85
# elevation.start = 85
# elevation.end = 89
# elevation = [ 30.0, 60.0, 90.0 ]

[rocket]
name	= "example rocket"
type	= "hybrid"

[[rocket.stage]]
engine	= "20191020_01.eng"
length	= 1.1540
diameter= 0.112
mass	= 5.035
I0		= 1.254
If		= 1.251
lcg0	= 0.913
lcgf	= 0.905
lcp		= 1.141
Cd		= 0.440
Cna		= 7.840
parachute= {condition = "top", delay = 2.5}
