[simulation]
dt			= 0.01
output.dt	= 0.01
output.dir	= "output"

[launcher]
length	= 5
elevation	= 85
# elevation.start = 85
# elevation.end = 89
# elevation = [ 80.0, 80.1, 80.2, 80.3 ]

[rocket]
name	= "example rocket"
type	= "hybrid"

[[rocket.stage]]
engine	= "K240.eng"
length	= 1.1540
diameter= 0.112
mass	= 5.679
Cd		= 0.440
Cna		= 7.840
lcg0	= 0.913
lcgf	= 0.905
parachute= {condition = "top", delay = 2.5}
