name: Build

on:
  push:
    branches:
      - master
      - develop
      - feature/*
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1
    - name: prepare
      run: |
          cmake --help
          mkdir build
    - name: configure
      run: |
          cd build
          cmake ..
    - name: configure for windows
      if: matrix.os == 'windows-latest'
      run: |
          cd build
          cmake -G "NMake Makefiles" ..
    - name: build on ${{ matrix.os }}
      run: cmake --build build
