name: build

on:
  push:
    branches:
      - master
      - develop
      - feature/*
    tags:
      - v*

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build on ubuntu
      run: |
        mkdir build
        cd build
        cmake ..
        make

  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: build on macos
      run: |
        mkdir build
        cd build
        cmake ..
        make
