name: CI

on:
  push:
    branches:
      - master
      - develop
      - feature/*
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      if: matrix.os != 'windows-latest'
      run: |
          mkdir build
          cd build
          cmake ..
    - name: configure on windows
      if: matrix.os == 'windows-latest'
      run: |
          mkdir build
          cd build
          cmake -G "MSYS Makefiles" ..
    - name: build on ${{ matrix.os }}
      run: cmake --build build --parallel

    - name: make release file
      run: touch hoge
    - name: Release
      uses: JasonEtco/upload-to-release@master
      with:
        args: hoge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
