name: Build

on:
  push:
    branches:
      - master
      - develop
      - feature/*
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
          mkdir build
          cd build
          cmake ..
    - name: build on ${{ matrix.os }}
      run: |
          cd build
          make

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
          cmake --help
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..
    - name: build on ${{ matrix.os }}
      run: cmake --build build --parallel
